project:
  type: book
  # output-dir: docs

execute:
  echo: true

book:
  title: "Project Guide"
  author: "Kasper Munch"
  chapters:
    - index.qmd
    - part: "Project setup"
      chapters: 
      - guides/laptop_setup.qmd
      - guides/cluster_access.qmd
      - guides/cluster_setup.qmd
      - guides/reproducible.qmd
    - part: "Quickstarts"
      chapters: 
      - guides/git.qmd      
      - guides/gwf.qmd      
      - notebooks/00_jupyterlab.ipynb
      - guides/quarto.qmd      
    - part: "Notebooks"
      chapters: 
      - notebooks/01_weather.ipynb
      - notebooks/02_interaction.ipynb
    - part: "Reporting"
      chapters: 
      - reports/manuscript.qmd
      - reports/supplementary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
    toc-depth: 2
    number-sections: false


