project:
  type: book
  # output-dir: docs

execute:
  echo: true

book:
  title: "Project Guide"
  author: "Kasper Munch"
  chapters:
    - index.qmd
    - part: "Project setup"
      chapters: 
      - guides/laptop_setup.qmd
      - guides/cluster_access.qmd
      - guides/cluster_setup.qmd
      - guides/reproducible.qmd
    - part: "Quickstarts"
      chapters: 
      - guides/git.qmd      
      - guides/gwf.qmd      
      - guides/jupyter.qmd      
      - guides/quarto.qmd      
    - part: "Notebooks"
      chapters: 
      - notebooks/00_jupyterlab.ipynb
      - notebooks/01_getting_started.ipynb
      - notebooks/02_jupyter_and_quarto.ipynb
    - part: "Reporting"
      chapters: 
      - reports/manuscript.qmd
      - reports/supplementary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 2

