project:
  type: book
  # output-dir: docs

execute:
  echo: true

book:
  title: "Project Guide"
  author: "Kasper Munch"
  chapters:
    - index.qmd
    - part: "Project setup"
      chapters: 
      - guides/laptop_setup.qmd
      - guides/cluster_access.qmd
      - guides/cluster_setup.qmd
      - guides/reproducible.qmd
    - part: "Quickstarts"
      chapters: 
      - guides/git_101.qmd      
      - guides/jupyterlab.ipynb
      - guides/quarto.qmd
    - part: "Guides"
      chapters:
      - guides/gwf.qmd      
      - guides/git.qmd
      - guides/numpy_pandas.ipynb
      - guides/plotting.ipynb
      - guides/submodules.qmd
      - guides/pymc.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: default
    toc-depth: 2
    number-sections: false


