# Introduction {.unnumbered}

These pages are generated from Git repository (more about that later). The repository serves both as a source of practial information to get you started, and as a scaffold for your project. Once you have copied it and made it your own, you populate with your own text, code, analysis notebooks, and documentation. For now most of what you see are placeholders for what will eventually be your own contributions.

## Project outline

Here you should write a paragraph outlining the project to the extent you can at this point. What are the goals of your project? What would you like to find out? What would you like to learn? You should update it along the way.

## Project plan

Here you should outline project plan and what you intend to do in the weeks/months of your project. This is ofcause tentative and will change along the way. But it is important that it changes because you decide it is meaningful.

1.  The first month is allocated to ...
2.  The second month ...
3.  
4.  
5.  The last month ...

## Suggested reading

These are some suggestions for background reading. If you want to some reading before you begin the project, focus on textbook population genetic basics. I will guide you to more relevant reads once you get started.

- [Nielsen and Slatkin's "An Introduction to Population Genetics: Theory and Applications"](https://www.amazon.com/Introduction-Population-Genetics-Theory-Applications/dp/1605351539) is a good introduction to the basics of population genetics.
- [Graham Coop's Lecture notes](https://github.com/cooplab/popgen-notes) are also a good basic introduction (and is free).
- [Genetic Villains: Killer Meiotic Drivers](https://doi.org/10.1016/j.tig.2018.02.003), is a review on meiotic drive.
- [Extraordinary selection on the human X chromosome associated with archaic admixture](10.1016/j.xgen.2023.100274) is our most recent paper on the topic.