
# Quarto reporting {#sec-quarto}


You can install Quarto for a single user on Linux by using the Quarto tarball and following the below set of steps. First login to the cluster and download the tarball:

```txt
wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.547/quarto-1.4.547-linux-amd64.tar.gz
```

Then extract the contents of the tarball to the location where you typically install software. Like:

```txt
mkdir ~/opt
tar -C ~/opt -xvzf quarto-1.4.547-linux-amd64.tar.gz
```

Create a symlink to bin/quarto in a folder that is in your path. If there is no such folder, you can create a folder such as ~/bin and place the symlink there. For example:

```txt
mkdir ~/bin
ln -s ~/opt/quarto-1.4.547/bin/quarto ~/bin/quarto
```

Either add Add folder with quarto to the list of folders where linux searches for executables:

```txt
( echo ""; echo 'export PATH=$PATH:~/bin\n' ; echo "" ) >> ~/.profile
source ~/.profile
```

Check The Installation

Use quarto check to confirm that the installation is successful:

```txt
quarto check
```

# Render your content

Go to the root of your repository (_where the `_quarto.yml` file is). Acitvate your conda environment and run this command to execute and render your content as html pages.

```txt
quarto render --execute
```

# One-time publish setup

The way your repository is set up, GitHub will automatically render (but not execute) and publish your content every time you push changes. But you need to run the command below *once* to allow quarto to do some initial setup and configuration.

```txt
quarto publish gh-pages
```